package kiro

import (
	"encoding/json"
	"errors"
	"net/http"
	"os"
	"strings"
	"testing"
)

// The expected examples were generated by the pinned reference converter with
// synthetic inputs, not by wireBody or wireExamples in this implementation.
func TestWireMatchesIndependentReferenceExamples(t *testing.T) {
	b, err := os.ReadFile("testdata/reference-requests.json")
	if err != nil {
		t.Fatal(err)
	}
	var fixture struct {
		Commit      string            `json:"reference_commit"`
		Hostname    string            `json:"synthetic_hostname"`
		Username    string            `json:"synthetic_username"`
		Fingerprint string            `json:"synthetic_fingerprint"`
		Headers     map[string]string `json:"header_examples"`
		Requests    []json.RawMessage `json:"request_examples"`
	}
	if err := json.Unmarshal(b, &fixture); err != nil {
		t.Fatal(err)
	}
	if fixture.Commit != "a5292ca04c7c6231e0b47673ac3f981f5a706e1e" || len(fixture.Requests) != 6 {
		t.Fatal("reference fixture must contain six requests from the pinned commit")
	}
	if got := wireClientFingerprint(fixture.Hostname, fixture.Username); got != fixture.Fingerprint {
		t.Errorf("wireClientFingerprint(synthetic host/user) = %q, want %q", got, fixture.Fingerprint)
	}
	headers, err := wireHeaders(fixture.Fingerprint, fixture.Headers["amz-sdk-invocation-id"])
	if err != nil {
		t.Fatal(err)
	}
	headers.Set("Authorization", "Bearer sentinel-token")
	for name, want := range fixture.Headers {
		if got := headers.Get(name); got != want {
			t.Errorf("reference header %s = %q, want %q", name, got, want)
		}
		delete(headers, http.CanonicalHeaderKey(name))
	}
	if headers.Get("Accept") != "*/*" || headers.Get("Accept-Encoding") != "identity" || len(headers) != 2 {
		t.Errorf("extra headers = %v, want only reviewed Accept and identity encoding", headers)
	}
	examples, err := wireExamples()
	if err != nil || len(examples) != 6 {
		t.Fatalf("wireExamples() count=%d error=%v, want six and nil", len(examples), err)
	}
	for i := range examples {
		if !samePlanValue(examples[i], fixture.Requests[i]) {
			t.Errorf("wireExamples(%s) differs from independently generated reference request: got %s want %s", fixtureCaseIDs[i], examples[i], fixture.Requests[i])
		}
	}
}

func TestWireHeadersRejectMalformedIdentity(t *testing.T) {
	for _, tc := range []struct{ fingerprint, invocation string }{
		{"", wireTestID},
		{strings.Repeat("g", 64), wireTestID},
		{strings.Repeat("0", 64), ""},
		{strings.Repeat("0", 64), "00000000-0000-1000-8000-000000000001"},
		{strings.Repeat("0", 64), "00000000-0000-4000-0000-000000000001"},
		{strings.Repeat("0", 64), "00000000-0000-4000-8000-00000000\r\nx"},
	} {
		if _, err := wireHeaders(tc.fingerprint, tc.invocation); !errors.Is(err, errPlanInvalid) {
			t.Errorf("wireHeaders(malformed synthetic identity) error=%v, want plan_invalid", err)
		}
	}
	seen := make(map[string]bool)
	for range 6 {
		id, err := wireUUID()
		if err != nil {
			t.Fatal(err)
		}
		if _, err := wireHeaders(strings.Repeat("0", 64), id); err != nil || seen[id] {
			t.Fatalf("wireUUID() repeated or invalid ID: error=%v", err)
		}
		seen[id] = true
	}
}
